---
# tasks file for apigee-opdk-extension-ds
- name: Nodetool flush before repair
  shell: '{{ nodetool }} flush'
  environment:
    JAVA_HOME: '{{ java_home }}'

- name: Rebuild Cassandra nodes
  shell: '{{ nodetool }} -h {{ private_address }} rebuild dc-{{ region_num }}'
  environment:
    JAVA_HOME: '{{ java_home }}'

- name: Nodetool flush after repair
  shell: '{{ nodetool }} flush'
  environment:
    JAVA_HOME: '{{ java_home }}'

